# Generated by Django 4.2.6 on 2023-10-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('birth_date', models.DateField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
