# Generated by Django 4.2.6 on 2023-10-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmassage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
