# Generated by Django 4.2.6 on 2023-10-25 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_unread_messages_and_more'),
        ('massage', '0003_chatmassage_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmassage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='users.userprofile'),
        ),
    ]
