# Generated by Django 4.2.6 on 2023-10-24 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending'), ('waiting', 'Waiting')], max_length=20)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
                ('shared_users', models.ManyToManyField(related_name='shared_forms', to='users.userprofile')),
            ],
        ),
    ]
