# Generated by Django 4.2.6 on 2023-10-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_person_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(related_name='parents', to='people.person'),
        ),
    ]
