# Generated by Django 4.2.6 on 2023-10-24 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.basicform')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
