# Generated by Django 4.2.6 on 2023-10-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0003_chatmassage_recipient'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='unread_messages',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unread_messages',
            field=models.ManyToManyField(related_name='unread_for', to='massage.chatmassage'),
        ),
    ]
